### ISSUE TITLE
macOS无法登陆了

### ISSUE THREAD

**Issue by gsmlg** [qjfoidnh/BaiduPCS-Go#126]
登录之后爆栈

```
panic: runtime error: slice bounds out of range [:11] with capacity 1

goroutine 1 [running]:
bytes.Replace({0xc00020ecc0, 0xc00020ecc0, 0x31}, {0xc0003baee7, 0xc0003baed8, 0x1}, {0x0, 0x0, 0xc0003baf50}, 0xffffffffffffffff)
	bytes/bytes.go:1017 +0x53c
github.com/qjfoidnh/baidu-tools/tieba/tiebautil.TiebaClientRawQuerySignature({0xc00020ecc0, 0x31})
	github.com/qjfoidnh/baidu-tools@v0.0.0-20201218182636-dfa5778abeed/tieba/tiebautil/client_signature.go:59 +0xc7
github.com/qjfoidnh/baidu-tools/tieba.NewUserInfoByUID(0x524ca402)
	github.com/qjfoidnh/baidu-tools@v0.0.0-20201218182636-dfa5778abeed/tieba/tieba_info.go:19 +0xd3
github.com/qjfoidnh/baidu-tools/tieba.(*Tieba).FlushUserInfo(0xc0004f4c00)
	github.com/qjfoidnh/baidu-tools@v0.0.0-20201218182636-dfa5778abeed/tieba/tieba_info.go:86 +0x8c
github.com/qjfoidnh/baidu-tools/tieba.NewUserInfoByBDUSS({0xc00043e366, 0xc0004d50e0})
	github.com/qjfoidnh/baidu-tools@v0.0.0-20201218182636-dfa5778abeed/tieba/tieba_login.go:68 +0xd54
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsconfig.NewUserInfoByBDUSS({0xc00043e366, 0xc000219bd0})
	github.com/qjfoidnh/BaiduPCS-Go/internal/pcsconfig/baidu.go:88 +0x27
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsconfig.(*PCSConfig).SetupUserByBDUSS(0xc00014cb40, {0xc00043e366, 0x0}, {0xc0000cc127, 0x20}, {0xc0001490a7, 0x40}, {0xc00044ee00, 0xc00014cb40})
	github.com/qjfoidnh/BaiduPCS-Go/internal/pcsconfig/maniper.go:124 +0xcf
main.main.func5(0xc0005a4160)
	github.com/qjfoidnh/BaiduPCS-Go/main.go:441 +0x277
github.com/urfave/cli.HandleAction({0x15315a0, 0x16166f0}, 0x5)
	github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0x15e5587, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x15ef8a7, 0x12}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).Run(0xc0001788c0, {0xc00059a000, 0x2, 0x2})
	github.com/urfave/cli@v1.22.5/app.go:277 +0x705
main.main.func1(0xc00013a2c0)
	github.com/qjfoidnh/BaiduPCS-Go/main.go:323 +0x545
github.com/urfave/cli.HandleAction({0x1529300, 0xc000218750}, 0xc0001788c0)
	github.com/urfave/cli@v1.22.5/app.go:526 +0x50
github.com/urfave/cli.(*App).Run(0xc0001788c0, {0xc000020200, 0x1, 0x1})
	github.com/urfave/cli@v1.22.5/app.go:286 +0x625
main.main()
	github.com/qjfoidnh/BaiduPCS-Go/main.go:2204 +0x6545
```

**Comment by qjfoidnh** [comment]
本地未能复现，如果重试后问题仍在可再反馈

**Comment by gsmlg** [comment]
另一台mac也会如此
系统版本
```
ProductName:	macOS
ProductVersion:	12.0
BuildVersion:	21A5304g
```

这个是测试系统，前两天更新之后，这个登录出错

**Comment by qjfoidnh** [comment]
https://github.com/qjfoidnh/BaiduPCS-Go/actions/runs/1189222132

这里的版本再试试

**Comment by gsmlg** [comment]
这个版本的没有问题

> https://github.com/qjfoidnh/BaiduPCS-Go/actions/runs/1189222132
> 
> 这里的版本再试试

**Comment by ufbycd** [comment]
Manjaro Linux系统也是如此：

baidupcs -v 
`BaiduPCS-Go version v3.8.3-devel`

uname -a
`Linux ManjaroMSI 5.10.68-1-MANJARO #1 SMP PREEMPT Wed Sep 22 12:29:47 UTC 2021 x86_64 GNU/Linux`
