### ISSUE TITLE
上传文件出错，fatal error: sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by ghost** [qjfoidnh/BaiduPCS-Go#138]
``` bash
fatal error: sync: unlock of unlocked mutex

goroutine 13255 [running]:
runtime.throw(0xab94bd, 0x1e)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0303cdb28 sp=0xc0303cdaf8 pc=0x436192
sync.throw(0xab94bd, 0x1e)
        /usr/local/go/src/runtime/panic.go:1103 +0x35 fp=0xc0303cdb48 sp=0xc0303cdb28 pc=0x467775
sync.(*Mutex).unlockSlow(0xc01fec06d0, 0xffffffff)
        /usr/local/go/src/sync/mutex.go:196 +0xd8 fp=0xc0303cdb70 sp=0xc0303cdb48 pc=0x483118
sync.(*Mutex).Unlock(...)
        /usr/local/go/src/sync/mutex.go:190
github.com/qjfoidnh/BaiduPCS-Go/baidupcs/expires/cachemap.(*cacheUnit).UnlockKey(0xc00007a050, 0x9d7c00, 0xc01fdcf830)
        /home/liu/Projects/BaiduPCS-Go/baidupcs/expires/cachemap/cacheunit.go:80 +0xac fp=0xc0303cdbc0 sp=0xc0303cdb70 pc=0x6f16ec
github.com/qjfoidnh/BaiduPCS-Go/baidupcs/expires/cachemap.(*CacheOpMap).CacheOperation(0xc000174570, 0xab978d, 0x1e, 0x9d7c00, 0xc01fdcf830, 0xc0303cdca8, 0xb70e78, 0xc01f7c7640)
        /home/liu/Projects/BaiduPCS-Go/baidupcs/expires/cachemap/utils.go:26 +0x1e2 fp=0xc0303cdc50 sp=0xc0303cdbc0 pc=0x6f1902
github.com/qjfoidnh/BaiduPCS-Go/baidupcs.(*BaiduPCS).CacheFilesDirectoriesList(0xc000174510, 0xc0046c2680, 0x4b, 0xebd260, 0xc020110000, 0x1c4, 0x200, 0x0, 0x0)
        /home/liu/Projects/BaiduPCS-Go/baidupcs/cache.go:24 +0x1b6 fp=0xc0303cdcf0 sp=0xc0303cdc50 pc=0x868956
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadTaskUnit).rapidUpload(0xc0046d0000, 0x0, 0x0)
        /home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_task_unit.go:104 +0x92 fp=0xc0303cdea8 sp=0xc0303cdcf0 pc=0x921c72
github.com/qjfoidnh/BaiduPCS-Go/internal/pcsfunctions/pcsupload.(*UploadTaskUnit).Run(0xc0046d0000, 0x0)
        /home/liu/Projects/BaiduPCS-Go/internal/pcsfunctions/pcsupload/upload_task_unit.go:345 +0x274 fp=0xc0303cdf78 sp=0xc0303cdea8 pc=0x9235f4
github.com/qjfoidnh/BaiduPCS-Go/pcsutil/taskframework.(*TaskExecutor).Execute.func1(0xc01af0e960, 0xc0002df230, 0xc004577da0)
        /home/liu/Projects/BaiduPCS-Go/pcsutil/taskframework/executor.go:94 +0x62 fp=0xc0303cdfc8 sp=0xc0303cdf78 pc=0x892b02
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0303cdfd0 sp=0xc0303cdfc8 pc=0x46c421
created by github.com/qjfoidnh/BaiduPCS-Go/pcsutil/taskframework.(*TaskExecutor).Execute
        /home/liu/Projects/BaiduPCS-Go/pcsutil/taskframework/executor.go:91 +0x7c
```

**Comment by chery2909157580** [comment]
相同错误

**Comment by chery2909157580** [comment]
https://github.com/golang/go/issues/26480

**Comment by Christoo1** [comment]
same error
