### ISSUE TITLE
Programe Crashed!

### ISSUE THREAD

**Issue by boyodyang** [qjfoidnh/BaiduPCS-Go#184]
[976] 准备下载: /Music/无损音源/1。DSD/DSD 爵士乐/Dennis Kolen - Northeim Goldmine/04 - Dennis Kolen - For Cloud Dog And Jane.dff
[976] 文件已经存在: /root/Downloads/30220048_boyod/DSD 爵士乐/Dennis Kolen - Northeim Goldmine/04 - Dennis Kolen - For Cloud Dog And Jane.dff, 跳过...

[977] ----
  类型              文件                                                                                                 
  文件路径          /Music/无损音源/1。DSD/DSD 爵士乐/Concord Picante - La Onda Va Bien/03 - Cal Tjader - Star Eyes.dff  
  文件名称          03 - Cal Tjader - Star Eyes.dff                                                                      
  文件大小          79614806, 75.926596MB                                                                                
  md5 (截图请打码)  9c09a49cb183975df3e9af95c76f7770                                                                     
  app_id            250528                                                                                               
  fs_id             1063312741928385                                                                                     
  创建日期          2014-07-22 04:30:10                                                                                  
  修改日期          2021-08-03 19:31:00                                                                                  

[977] 准备下载: /Music/无损音源/1。DSD/DSD 爵士乐/Concord Picante - La Onda Va Bien/03 - Cal Tjader - Star Eyes.dff
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1b4094]

goroutine 1255 [running]:
net.(*Resolver).tryOneName(0xc21820, 0x7a0400, 0x40000b6000, 0x40001e6640, 0x40002d6060, 0x10, 0x400045001c, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dnsclient_unix.go:254 +0x204
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0xc21820, 0x7a0400, 0x40000b6000, 0x40001e6640, 0x40002d6060, 0x10, 0x40002eec60, 0x63001c)
        /usr/local/go/src/net/dnsclient_unix.go:602 +0x60
created by net.(*Resolver).goLookupIPCNAMEOrder.func3
        /usr/local/go/src/net/dnsclient_unix.go:601 +0xb4
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1b4094]

goroutine 1254 [running]:
net.(*Resolver).tryOneName(0xc21820, 0x7a0400, 0x40000b6000, 0x40001e6640, 0x40002d6060, 0x10, 0x4000450001, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dnsclient_unix.go:254 +0x204
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0xc21820, 0x7a0400, 0x40000b6000, 0x40001e6640, 0x40002d6060, 0x10, 0x40002eec60, 0x630001)
        /usr/local/go/src/net/dnsclient_unix.go:602 +0x60
created by net.(*Resolver).goLookupIPCNAMEOrder.func3
        /usr/local/go/src/net/dnsclient_unix.go:601 +0xb4
root@L1Pro:~/BaiduPCS# free
              total        used        free      shared  buff/cache   available
Mem:        1001076      319592      290484       12904      391000      593356
Swap:       1201972       55296     1146676

**Comment by qjfoidnh** [comment]
已知问题，推测跟系统dns配置有关，因为无法稳定复现所以一直未得到解决

**Comment by boyodyang** [comment]
[3408] 准备下载: /Music/无损音源/3。DTS+ACG+影视/环绕多声道/DTS格式环绕/5/DTS-CD-945：群星《迎春接福(民乐)》/05. 拜年.dts
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1a1514]

goroutine 3661 [running]:
net.(*Resolver).tryOneName(0xa1d540, 0x6b6118, 0x400220a840, 0x4000280500, 0x40022667b0, 0x11, 0x1001c, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dnsclient_unix.go:253 +0x1e4
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0xa1d540, 0x6b6118, 0x400220a840, 0x4000280500, 0x40022667b0, 0x11, 0x4001fdd500, 0x59001c)
        /usr/local/go/src/net/dnsclient_unix.go:601 +0x7c
created by net.(*Resolver).goLookupIPCNAMEOrder.func3
        /usr/local/go/src/net/dnsclient_unix.go:600 +0xb4

**Comment by boyodyang** [comment]
连续出现!

[3342] 准备下载: /Music/无损音源/3。DTS+ACG+影视/环绕多声道/DTS格式环绕/2/DTS-CD-563：披头士乐队(The Beatles)《Five Point Wonderful-CD4》/11.Don't Let Me Down.dts
[3342] 文件已经存在: /root/Downloads/30220048_boyod/环绕多声道/DTS格式环绕/2/DTS-CD-563：披头士乐队(The Beatles)《Five Point Wonderful-CD4》/11.Don't Let Me Down.dts, 跳过...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1a1514]

goroutine 3591 [running]:
net.(*Resolver).tryOneName(0xa1d540, 0x6b6118, 0x400042e8c0, 0x400026a5a0, 0x4001e084b0, 0x11, 0x1001c, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dnsclient_unix.go:253 +0x1e4
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0xa1d540, 0x6b6118, 0x400042e8c0, 0x400026a5a0, 0x4001e084b0, 0x11, 0x40009e2f00, 0x59001c)
        /usr/local/go/src/net/dnsclient_unix.go:601 +0x7c
created by net.(*Resolver).goLookupIPCNAMEOrder.func3
        /usr/local/go/src/net/dnsclient_unix.go:600 +0xb4
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1a1514]



goroutine 3590 [running]:
net.(*Resolver).tryOneName(0xa1d540, 0x6b6118, 0x400042e8c0, 0x400026a5a0, 0x4001e084b0, 0x11, 0x10001, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dnsclient_unix.go:253 +0x1e4
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0xa1d540, 0x6b6118, 0x400042e8c0, 0x400026a5a0, 0x4001e084b0, 0x11, 0x40009e2f00, 0x590001)
        /usr/local/go/src/net/dnsclient_unix.go:601 +0x7c
created by net.(*Resolver).goLookupIPCNAMEOrder.func3
        /usr/local/go/src/net/dnsclient_unix.go:600 +0xb4

**Comment by qjfoidnh** [comment]
可以发下你的操作系统版本，dns配置看看
另外有条件可以用go1.17编译试试，有可能是go本身问题
