### ISSUE TITLE
Please update dependencies to fix segment faults

### ISSUE THREAD

**Issue by rosaceous** [qjfoidnh/BaiduPCS-Go#239]
The binary failed to run with following error messages:

```
baidupcs@baidupcs ~/repo/BaiduPCS-Go $ ./BaiduPCS-Go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8621c6]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc0001ca000?, {0xc00017a480?, 0x270?, 0x24?}, 0x40?)
	<autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0xb13e00, 0xc0000bb580}, 0x210)
	/usr/lib/go/src/archive/zip/reader.go:526 +0xf5
archive/zip.(*Reader).init(0xc000147570, {0xb13e00?, 0xc0000bb580}, 0x210)
	/usr/lib/go/src/archive/zip/reader.go:97 +0x5c
archive/zip.NewReader({0xb13e00, 0xc0000bb580}, 0x210)
	/usr/lib/go/src/archive/zip/reader.go:90 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0xb14d60?, 0xc0000b02d8}, 0xf74efc)
	/home/baidupcs/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:128 +0x8b
github.com/daaku/go%2ezipexe.NewReader({0xb14d60, 0xc0000b02d8}, 0x0?)
	/home/baidupcs/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:48 +0x98
github.com/daaku/go%2ezipexe.OpenCloser({0xc0000f0450?, 0xc0000ebab0?})
	/home/baidupcs/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:30 +0x57
github.com/GeertJohan/go%2erice.init.0()
	/home/baidupcs/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.2/appended.go:42 +0x65
```

To fix the runtime error,  the dependency daaku/go.zipexe should be updated to the version 1.0.2

**Comment by qjfoidnh** [comment]
done
