### ISSUE TITLE
目录比较大时，下载被阻塞，无法实施。

### ISSUE THREAD

**Issue by boyodyang** [qjfoidnh/BaiduPCS-Go#89]
500G内容以上的目录，没有任何输出一直。
搞得我得把一个目录里的内容分批分次才能全下载完。
不知道是什么问题。大于500G一直都没有获取到下载列表。

谢谢

**Comment by qjfoidnh** [comment]
问题大概率出在文件总数上，能否提供一下总文件数，总目录数，最好还有目录的最大深度？

**Comment by boyodyang** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1b4094]

goroutine 309 [running]:
net.(*Resolver).tryOneName(0xc21820, 0x7a0400, 0x40001ce740, 0x40001d2640, 0x4000465800, 0x15, 0x1c, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dnsclient_unix.go:254 +0x204
net.(*Resolver).goLookupIPCNAMEOrder.func3.1(0xc21820, 0x7a0400, 0x40001ce740, 0x40001d2640, 0x4000465800, 0x15, 0x40002e1ce0, 0x63001c)
        /usr/local/go/src/net/dnsclient_unix.go:602 +0x60
created by net.(*Resolver).goLookupIPCNAMEOrder.func3
        /usr/local/go/src/net/dnsclient_unix.go:601 +0xb4

**Comment by boyodyang** [comment]
谢谢你的回复。
这次干脆报错退出了。
日志在这里，有可能是内存耗尽
https://drive.google.com/file/d/1aNCAPWWMmFohOMfXOljF4nAseK-c0PHT/view?usp=sharing

**Comment by boyodyang** [comment]
> 问题大概率出在文件总数上，能否提供一下总文件数，总目录数，最好还有目录的最大深度？
> […](#)
> 在 2021年6月27日，下午4:50，boyodyang ***@***.***> 写道： ﻿ 我下载大概200多G的内容的目录基本没问题。 400G内容以上的目录，就会进程锁死，没有任何输出一直。 搞得我得把一个目录里的内容分批分次才能全下载完。 不知道是什么问题。 谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


目录深度应该不深，最多5层，文件估计有5000多个，文件名比较长。都是歌曲，超过500G就比较困难了。一般一首歌30M

**Comment by qjfoidnh** [comment]
看日志像dns解析的问题，这个我可能要花点时间研究一下

**Comment by boyodyang** [comment]
> 看日志像dns解析的问题，这个我可能要花点时间研究一下

谢谢，在新加坡下载的。 一般感觉小一点目录都没问题，超过1T很容易阻塞。
有时也会有这样的错误，获取目录下的文件列表: 网络错误, Get https://pcs.baidu.com/rest/2.0/pcs/file?app_id=266719&by=name&limit=0-2147483647&method=list&order=asc&path=%2FMusic%2F%E6%97%A0%E6%8D%9F%E9%9F%B3%E6%BA%90%2F4%E3%80%82WAV%2B%E6%AF%8D%E5%B8%A6%2BHiRes: net/http: TLS handshake timeout

**Comment by boyodyang** [comment]
基本确定25000文件以上的文件夹，下载会有大概率被阻塞。

**Comment by boyodyang** [comment]
> 问题大概率出在文件总数上，能否提供一下总文件数，总目录数，最好还有目录的最大深度？
> […](#)
> 在 2021年6月27日，下午4:50，boyodyang ***@***.***> 写道： ﻿ 我下载大概200多G的内容的目录基本没问题。 400G内容以上的目录，就会进程锁死，没有任何输出一直。 搞得我得把一个目录里的内容分批分次才能全下载完。 不知道是什么问题。 谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

经过测试，基本确定20000文件以上的文件夹，下载会有概率被阻塞。30000文件以上的文件夹，下载会有大概率被阻塞。目录深度大概6以内。
